export { cache } from './core/cache.js';
export { clear } from './core/clear.js';
export { deleteAsync as delete } from './core/delete.js';
export { entries } from './core/entries.js';
export { forEach } from './core/forEach.js';
export { get } from './core/get.js';
export { has } from './core/has.js';
export { keys } from './core/keys.js';
export { set } from './core/set.js';
export { size } from './core/size.js';
export { values } from './core/values.js';
